### ISSUE TITLE
Error: failed to parse date field

### ISSUE THREAD

**Issue by gtapps** [babenkoivan/elastic-scout-driver#1]
Hello,
I'm trying to do the following query:
`$query->where('created_at', '>=', Carbon::today()->subDays(7)->toIso8601String());`

And I'm getting the following error:
[{"type":"parse_exception","reason":"failed to parse date field [>=] with format [strict_date_optional_time||epoch_millis]: [failed to parse date field [>=] with format [strict_date_optional_time||epoch_millis]]"}],"type":"search_phase_execution_exception","reason":"all shards failed","phase":"query","grouped":true,"failed_shards":[{"shard":0,"index":"cs_posts","node":"pogCjDffQQyxxBvc4USyXQ","reason":{"type":"query_shard_exception","reason":"failed to create query: failed to parse date field [>=] with format [strict_date_optional_time||epoch_millis]: [failed to parse date field [>=] with format [strict_date_optional_time||epoch_millis]]","index_uuid":"_lAWBj-pSe2phJ5dg2pazQ...

I even tried to store the created_at value like this in the toSearchableArray() function
`$this->created_at->toIso8601String()

But I always get this error.
Any idea on how to overcome this?

Thank you,
Gabriel

**Comment by babenkoivan** [comment]
Hi @gtapps,

`where` method expects only 2 arguments - https://laravel.com/docs/7.x/scout#where-clauses

If you want to make a more complex search query, please check the [elastic-scout-driver-plus](https://github.com/babenkoivan/elastic-scout-driver-plus) extension.

Also make sure, that `created_at` has a proper mapping format - https://www.elastic.co/guide/en/elasticsearch/reference/current/mapping-date-format.html
