### ISSUE TITLE
PHP 8.0 support

### ISSUE THREAD

**Issue by sicaboy** [babenkoivan/elastic-scout-driver#11]

**Comment by adithyasrinivasan** [comment]
Elasticsearch has just released the PHP8 compatible update.

Thanks for the work!

**Comment by sicaboy** [comment]
Thanks.

**Comment by babenkoivan** [comment]
Reopening as PHP 8 support hasn't been yet added to this package.

**Comment by babenkoivan** [comment]
PHP support has been added in [v1.3.0](https://github.com/babenkoivan/elastic-scout-driver/releases/tag/v1.3.0) 🎉
