### ISSUE TITLE
Rooting parameter for join functionality

### ISSUE THREAD

**Issue by luciegirard** [babenkoivan/elastic-scout-driver#13]
I'm trying to do a join by setting a parent/child relationship and I must set the rooting with the parent id in the URL to do it as explained in the documentation of ElasticSearch[1]. I've seen that ElasticAdapter only take body parameter before calling bulk function and no parameter is provided for rooting[2].
So is it possible to do it ? I can fork your work and try to resolve the problem by making a commit in few time if you want.

[1] https://www.elastic.co/guide/en/elasticsearch/reference/current/parent-join.html
[2] https://github.com/babenkoivan/elastic-adapter/blob/master/src/Documents/DocumentManager.php#L34

**Comment by luciegirard** [comment]
I've done this first implementation but I'm open to other ways to do it differently[1].

[1] https://github.com/babenkoivan/elastic-adapter/pull/6

**Comment by babenkoivan** [comment]
Hi @luciegirard, can you describe to me a use case? `join` type is rarely used due to performance, and maybe this is not what you are looking for. 

In addition, I think passing `routing` via document content is not a good idea as it doesn't belong there.

**Comment by luciegirard** [comment]
I'm trying to raise the priority of results with a parent by using has_child in a query (in Eloquent it's a many-to-one relation). So, to make the relations between objects, according to the documentation, I have to define the routing attribute which is impossible without it.

**Comment by babenkoivan** [comment]
@luciegirard you can index your parents and children separately (i.e. they would be stored in different indexes) and then use [join](https://github.com/babenkoivan/elastic-scout-driver-plus/blob/master/docs/generic-methods.md#join) along with [boostIndex](https://github.com/babenkoivan/elastic-scout-driver-plus/blob/master/docs/generic-methods.md#boostindex) methods. This would allow you to search for parents and children using a single query and boost parent results.

**Comment by luciegirard** [comment]
@babenkoivan, I understand this solution but this only works when parents and children are not on the same index, and in my case this can not work unfortunately. 🤔

**Comment by babenkoivan** [comment]
@luciegirard if you want to store both parents and children in the same index, you can use the [nested type](https://www.elastic.co/guide/en/elasticsearch/reference/current/nested.html) for children and [boost](https://www.elastic.co/guide/en/elasticsearch/reference/current/mapping-boost.html#mapping-boost) necessary parent fields.

**Comment by babenkoivan** [comment]
Custom routing is now supported in `elastic-scout-driver-plus` starting from [v2.2.0](https://github.com/babenkoivan/elastic-scout-driver-plus/releases/tag/v2.2.0) 🎉
