### ISSUE TITLE
Bulk Indexing

### ISSUE THREAD

**Issue by otherperspectives** [babenkoivan/elastic-scout-driver#14]
Hi there,

Is it possible to make the synchronization of Laravel Scout to be bulk?
We have millions of data records and if we make a request for each data entry, it will overwhelm our ES server.
At the moment we are using only ElasticSearch without saving the data in our MySQL. ( We are fetching data from multiple sources, and have thousands of records per hour inserted in our ES server. ) 
Do you think is a good idea to save first the data in our MySQL database, and after letting Laravel Scout make the synchronization?

**Comment by babenkoivan** [comment]
Hi @otherperspectives, it's bulk by default. 

Note though, when you do `$model->save()`, then the bulk contains only one operation, but if you do `$models->searchable()`, then the whole collection will be indexed via one request.

As for the second question, it should depend on your business logic, I can't really recommend anything here 🙂
