### ISSUE TITLE
Support Laravel Scout 9.0

### ISSUE THREAD

**Issue by VKambulov** [babenkoivan/elastic-scout-driver#16]
Hello! A new release of [Laravel Scout v9.0.0](https://github.com/laravel/scout/releases/tag/v9.0.0) has been released. If you update to it, then `ElasticScoutDriver` gives an error:
```
Class ElasticScoutDriver\Engine contains 3 abstract methods and must therefore be declared abstract or implement the remaining methods (Laravel\Scout\Engines\Engine::lazyMap, Laravel\Scout\Engines\Engine::createIndex, Laravel\Scout\Engines\Engine::deleteIndex)
```
I think it would be nice to continue supporting new versions of `Laravel Scout`.

**Comment by babenkoivan** [comment]
Hey @VKambulov, thank you for reporting! No doubts there will be Scout 9 support 😉

**Comment by stevebauman** [comment]
Thanks for your work on this @babenkoivan! ❤️ 

This has been incredibly easy to implement, and that's a testament to how well you've documented and built this 💪
