### ISSUE TITLE
Driver connection documentation

### ISSUE THREAD

**Issue by fernandocoronatomf** [babenkoivan/elastic-scout-driver#2]
Hi, thanks for providing the package.

I wonder where do I put the information for my cluster? I changed my scout driver to 'elastic' and trying to import the data but not sure how to connect to it.

Should I still use the array on scout.php?
```

 'algolia' => [
        'id' => env('ALGOLIA_APP_ID', ''),
        'secret' => env('ALGOLIA_SECRET', ''),
    ],
```

Thanks!

**Comment by babenkoivan** [comment]
Hey @fernandocoronatomf, thank you for pointing out to the missing part of the documentation!
I've updated the [Configuration](https://github.com/babenkoivan/elastic-scout-driver#configuration) section of the README file. Check it out!

**Comment by fernandocoronatomf** [comment]
Thanks. I figured it out after checking composer.json and the dependencies. 
But thanks for improving the docs anyway.

**Comment by fernandocoronatomf** [comment]
Also, @babenkoivan 
Can we configure the indexes using this package? What's your recommendation?

**Comment by babenkoivan** [comment]
@fernandocoronatomf have a look at [Elastic Migrations](https://github.com/babenkoivan/elastic-migrations) package 🙂
