### ISSUE TITLE
Removing usage of `final` classes

### ISSUE THREAD

**Issue by stevebauman** [babenkoivan/elastic-scout-driver#20]
Hi there!

I'm wondering if you may accept a PR removing the `final` declarations? I'm unable to extend anything in this package (or the scout-driver-plus package) without copying and pasting the whole class over and binding onto the interface -- negating the benefits of having this package be open source and community supported, since I can't utilize any of their base methods.

Is there a particular purpose for all classes to be `final`?

Thanks for your time!

**Comment by babenkoivan** [comment]
Hey @stevebauman,

Could you please share the link to your PR? I can't see it anywhere. 

Using `final` by default is a good approach to create closed interfaces, similarly to making all properties private, etc. I understand, that this might be overkill and not needed somewhere. You can just list the classes you need to extend and I remove `final` for those, but please don't remove it from all classes 🙂

**Comment by stevebauman** [comment]
Hey @babenkoivan!

> Could you please share the link to your PR? I can't see it anywhere.

I haven't submitted it -- I was asking the question before attempting to submit the PR incase it was something to be immediately rejected if it were to be against your programming paradigm.

> Using final by default is a good approach to create closed interfaces, similarly to making all properties private, etc

Does this benefit the usability and extendability of this package? From my current experience, it gate-keeps the underlying implementations, distrusting developers by preventing them from making any sort of adjustment necessary for their specific use-case or environment. It's also extremely hard to test with a partially-mocked implementation (i.e. `Mockery::makePartial()`), since final classes cannot be mocked.

> You can just list the classes you need to extend and I remove final for those, but please don't remove it from all classes

My main use-case is, I want to `extend` the built-in `SearchRequestFactory`, but I can't. I have to copy and paste the whole implementation and make my adjustment. This negates the power of an open-source package, as any update to the underlying implementation is now lost permanently unless I re-copy-and-paste after an update.

Please don't take this in a negative way -- I'm looking to seek your opinion on this matter as well as share my own experience.

Thanks for your time, and this package! ❤️

**Comment by babenkoivan** [comment]
@stevebauman I understand, that defining classes as `final` is controversial, but this is something I personally prefer. All classes in my packages are final unless there is a valid reason why they should be extended. 

Although it's always possible to create a decorator, I think it makes sense to remove `final` keyword from the following classes: `DocumentFactory`, `ModelFactory`, `SearchRequestFactory` and `Engine`. Would it be sufficient?

**Comment by babenkoivan** [comment]
@stevebauman `DocumentFactory`, `ModelFactory`, `SearchRequestFactory` and `Engine` are no longer `final` since [v1.3.1](https://github.com/babenkoivan/elastic-scout-driver/releases/tag/v1.3.1).

**Comment by stevebauman** [comment]
Thanks a lot @babenkoivan! I understand. 👍 

Really appreciate your support allowing these to be extended! ❤️  🙌
