### ISSUE TITLE
One or more operations in the bulk request did not complete successfully

### ISSUE THREAD

**Issue by mbuk** [babenkoivan/elastic-scout-driver#25]
| Software         | Version
| --------------| ---------------
| PHP                 | 7.4.19
| Elasticsearch  | 7.10.0
| Laravel            | 8.44.0
| Laravel Scout | 9.1.0

**Describe the bug**
Created a user record get the error: "One or more operations in the bulk request did not complete successfully" on saving

**To Reproduce**
Fresh docker image of elastic search 7.10 (cluster status: green - 3 nodes)

``` php artisan scout:index user_index ```

**Current behavior**
Error when saving
```
exception: "ElasticAdapter\\Exceptions\\BulkRequestException"
file: "<-snip->/vendor/babenkoivan/elastic-adapter/src/Documents/DocumentManager.php"
line: 51
message: "One or more operations in the bulk request did not complete successfully"
```
User model has trait Searchable and these methods:
 ```
   public function searchableAs()
    {
        return 'users_index';
    }

    public function toSearchableArray()
    {
        $array = $this->toArray();

        // Customize the data array...

        unset($array['password']);
        unset($array['remember_token']);

        return $array;
    }


    public function getScoutKey()
    {
        return $this->email;
    }

    public function getScoutKeyName()
    {
        return 'email';
    }
```

Record hits db but doesn't end up in the ES index

**Expected behavior**
Expected save to be successful and record stored in both DB & ElasticSearch

**Comment by geebengs** [comment]
I'm having this issue as well. Is this a version compatibility issue?

**Comment by mbuk** [comment]
@geebengs not sure but the versions I'm using seem to be supported when compared against compatibility in the readme:

- PHP 7.2-8.0
- Elasticsearch 7.0-7.10
- Laravel 6.x-8.x
- Laravel Scout 7.x-9.x

What versions are you running?

**Comment by babenkoivan** [comment]
Hi there, 

This exception just indicates that Ealsticsearch doesn't like the provided data. It's very likely, that the searchable array contains some fields, which do not correspond to the mapping, e.g. date fields have incorrect format.

You can catch the exception and check the Elasticsearch raw response, it should give you a clue on what is wrong:

```php
try {
    // your search query
} catch (BulkRequestException $e) {
    dd($e->getResponse());
}
```

**Comment by geebengs** [comment]
Thanks for your reply.
I was able to print out the real elastic search exception error and discovered that it had to do with a limited unused disk space on my computer, which caused elastic search to switch to read only mode.
Once I freed some space on my hard disk and ran a terminal command i found on stack over flow to reset elastic search out of read only mode, it began to work like a charm.
I really appreciate the work you out into this Amazon package and thanks for following up.

Sent from Yahoo Mail on Android 
 
  On Tue, 6 Jul 2021 at 8:26, Ivan ***@***.***> wrote:   


Hi there,

This exception just indicates that Ealsticsearch doesn't like the provided data. It's very likely, that the searchable array contains some fields, which do not correspond to the mapping, e.g. date fields have incorrect format.

You can catch the exception and check the Elasticsearch raw response, it should give you a clue on what is wrong:
try {
    // your search query
} catch (BulkRequestException $e) {
    dd($e->getResponse());
}

**Comment by mbuk** [comment]
@babenkoivan thanks I'll check it out - I'll close this an reopen if I can't sort it :)

Thanks again
