### ISSUE TITLE
toSearchableArray method not run for relationships

### ISSUE THREAD

**Issue by fadakar** [babenkoivan/elastic-scout-driver#26]
| Software         | Version
| --------------| ---------------
| PHP                 | 7.4.14
| Elasticsearch  | 7.13.2
| Laravel            | 8.40
| Laravel Scout | 9.1

**Describe the bug**

when I want to use a relationship that has its own toSearchableArray method, the toSearchableArray method doesn't run for relationships 

**To Reproduce**

**Current behavior**

**Expected behavior**

**Comment by babenkoivan** [comment]
Hey @fadakar, it sounds like a feature request to me. Can you share how your `toSearchableArray` looks like? I'm not quite sure I understand your use case.
