### ISSUE TITLE
support for where filters with operators

### ISSUE THREAD

**Issue by Orest-Divintari** [babenkoivan/elastic-scout-driver#28]
Will there be support for where filters with operators or more advanced where filter methods such as
```
where('age', '>=', 20);
```

```
whereBetween('age', [20, 30]);
```

**Comment by babenkoivan** [comment]
Hi @Orest-Divintari, you can consider installing [Elastic Scout Driver Plus](https://github.com/babenkoivan/elastic-scout-driver-plus), which provides various queries and filters. Check, for example, this [page](https://github.com/babenkoivan/elastic-scout-driver-plus/blob/master/docs/compound-queries.md#bool-filter).
