### ISSUE TITLE
no result  push in elastic

### ISSUE THREAD

**Issue by Cloner311** [babenkoivan/elastic-scout-driver#3]
| Software         | Version
| --------------| ---------------
| PHP                 | 7.3.19
| Elasticsearch  | 7.1.0
| Laravel            | 6.*
| Laravel Scout | 8.0

**Describe the bug**
hello , im using at **mongodb** from jenssegers/mongodb package .

after run command :
`php artisan scout:import "App\product"`

show result : 
Imported [App\product] models up to ID: 5e35949da49f04517147be86
Imported [App\product] models up to ID: 5e35949da49f04517147c07c
Imported [App\product] models up to ID: 5e35949ea49f04517147c277
.
.
.
Imported [App\product] models up to ID: 5ee4ac112407e012ce3bed42
Imported [App\product] models up to ID: 5ee89e5588d2b237f6052402
Imported [App\product] models up to ID: 5eeb3ac95083517cc7581892
All [App\product] records have been imported

but 
command : 
`curl 'localhost:9200/_cat/indices?v'`

show result:

health status index    uuid                   pri rep docs.count docs.deleted store.size pri.store.size
yellow open   products RIuEwO2_T6SBIwJviIurBA   1   1          0            0       283b           283b

( docs.count = 0  )
:(

my model : 

use Illuminate\Database\Eloquent\Model;
use Laravel\Scout\Searchable;
use Jenssegers\Mongodb\Eloquent\Model as Eloquent;

`class products extends Eloquent
{
    use Searchable;
    protected $collection = 'products';

    public function shouldBeSearchable()
    {
        return count($this->toSearchableArray()) > 0;
    }

    public function toSearchableArray()
    {
        $array = $this->toArray();

        // Customize array...

        return $array;
    }

}`

scout driver : 

`'driver' => env('SCOUT_DRIVER', 'elastic'),`

my code in web.php : 

Route::get('/', function () {
    $res = App\products::search('Asus')->get();
    dd($res);
});

But show result : 

Illuminate\Database\Eloquent\Collection {#270 ▼
  #items: []
}

please help me :(

**Comment by babenkoivan** [comment]
Hi @Cloner311, as you don't have any errors along the way, I can suggest 2 possible scenarios:

1. You enabled queues (https://laravel.com/docs/7.x/scout#queueing), but forgot to run the workers
2. `products:: toSearchableArray` returns an empty array

**Comment by Cloner311** [comment]
set searchable : 

` public function toSearchableArray()
    {
        $array = [
            '_id' => $this->_id,
            'enname' => $this->enname,
            'keyword' => $this->keyword
        ];

        // Customize array...

        return $array;
    }`

 Scout Qeue is false:

`'queue' => env('SCOUT_QUEUE', false),`

and import again

but result:

Illuminate\Database\Eloquent\Collection {#270 ▼
  #items: []
}

-----
Does it have anything to do with Mongodb?

**Comment by Cloner311** [comment]
Hi @babenkoivan  I found the bug.

 id in the mongodb is` _id`
And in toSearchableArray function, have to implement them as a 'id'

Thanks for developing a good package

**Comment by babenkoivan** [comment]
Hey @Cloner311, good finding!

I've added an exception in case  `_id` is returned by `toSearchableArray` to make the issue more visible and updated the README configuration section. It's a part of [v1.1.0](https://github.com/babenkoivan/elastic-scout-driver/releases/tag/v1.1.0) release.
