### ISSUE TITLE
TypeError : ElasticScoutDriver\Factories\DocumentFactory::makeFromModels(): Argument #1 ($models) must be of type Illuminate\Database\Eloquent\Collection

### ISSUE THREAD

**Issue by LastDragon-ru** [babenkoivan/elastic-scout-driver#30]
| Software         | Version
| --------------| ---------------
| PHP                 | 8.0.x
| Elasticsearch  | 7.13.4
| Laravel            | 8.52.0
| Laravel Scout | 9.2.3
| Scout Driver  | 1.4.0

**Describe the bug**

The latest version of the Scout extends all collections: ` \Illuminate\Support\Collection`, `Illuminate\Database\Eloquent\Collection`, etc, but the package support `Illuminate\Database\Eloquent\Collection` only. 

**To Reproduce**

```php
(new \Illuminate\Support\Collection([new Model()]))->searchable();
```

**Current behavior**

```
TypeError : ElasticScoutDriver\Factories\DocumentFactory::makeFromModels(): Argument #1 ($models) must be of type Illuminate\Database\Eloquent\Collection, Illuminate\Support\Collection given, called in /project/backend/vendor/babenkoivan/elastic-scout-driver/src/Engine.php on line 74
```

**Expected behavior**

No error.

**Comment by babenkoivan** [comment]
This will be fixed in the next version only because it requires an interface change and I know, that many people implemented `DocumentFactoryInterface`. ETA for the new version is this or next month.
