### ISSUE TITLE
Scout `whereIn` support

### ISSUE THREAD

**Issue by LastDragon-ru** [babenkoivan/elastic-scout-driver#31]
`whereIn` supported since https://github.com/laravel/scout/releases/tag/v9.2.1

**Comment by babenkoivan** [comment]
Hey @LastDragon-ru, I've added `whereIn` support in [v1.6.0](https://github.com/babenkoivan/elastic-scout-driver/releases/tag/v1.6.0) 🙂

**Comment by LastDragon-ru** [comment]
Great, thank you :)
