### ISSUE TITLE
how to use SearchRule?

### ISSUE THREAD

**Issue by shinnlu** [babenkoivan/elastic-scout-driver#35]
i just upgrade from scout-elasticsearch-driver, there is a syntax [Search Rules](https://github.com/babenkoivan/scout-elasticsearch-driver#search-rules)
how can i use it in this package?

**Comment by babenkoivan** [comment]
Hey @shinnlu, you also need to install [elastic-scout-driver-plus](https://github.com/babenkoivan/elastic-scout-driver-plus), which is shipped with the query builder. See the usage [here](https://github.com/babenkoivan/elastic-scout-driver-plus#query).

**Comment by shinnlu** [comment]
thank you for response, i will try it.
