### ISSUE TITLE
circuit_breaking_exception occuring when importing large datasets using `php artisan scout:import`

### ISSUE THREAD

**Issue by ArondeParon** [babenkoivan/elastic-scout-driver#36]
| Software         | Version
| --------------| ---------------
| PHP                 | 8.0.12
| Elasticsearch  | 7.15.0
| Laravel            | 8.68.1
| Laravel Scout | 9.3.1

**Describe the bug**
I have a catalog of +/- 30.000 objects that I want to import into ElasticSearch. When importing these using `php artisan scout:import`, I get the following error after a certain while:

```
  {"error":{"root_cause":[{"type":"circuit_breaking_exception","reason":"[parent] Data too large, data for [<http_request>] would be [8159653036/7.5gb], which is larger than the limit of [7789871104/7.2gb], real usage: [8159318912/7.5gb], new bytes reserved: [334124/326.2kb], usages [request=32643072/31.1mb, fielddata=426551/416.5kb, in_flight_requests=1171730/1.1mb, model_inference=0/0b, eql_sequence=0/0b, accounting=107056/104.5kb]","bytes_wanted":8159653036,"bytes_limit":7789871104,"durability":"TRANSIENT"}],"type":"circuit_breaking_exception","reason":"[parent] Data too large, data for [<http_request>] would be [8159653036/7.5gb], which is larger than the limit of [7789871104/7.2gb], real usage: [8159318912/7.5gb], new bytes reserved: [334124/326.2kb], usages [request=32643072/31.1mb, fielddata=426551/416.5kb, in_flight_requests=1171730/1.1mb, model_inference=0/0b, eql_sequence=0/0b, accounting=107056/104.5kb]","bytes_wanted":8159653036,"bytes_limit":7789871104,"durability":"TRANSIENT"},"status":429}
```

However, when I create a look and save each of the Laravel models individually, this error wil not trigger.

Is there any way around this?

**Comment by babenkoivan** [comment]
Hi @ArondeParon,

This is not a library issue, but rather Elasticsearch/JVM configuration or the data you are importing. You can either increase the JVM heap size, or reduce import chunks via the `scout.chunk` config, or exclude some fields that you don't need to index via the `toSearchableArray()` method. 

Hope this helps :)
