### ISSUE TITLE
Bulk or Single Index Settings

### ISSUE THREAD

**Issue by dannydinges** [babenkoivan/elastic-scout-driver#37]
Is there a reason for not implementing the Bulk or Single index options used by the config of the previous driver package that is archived? I have some large documents that I like to pull up in bulk with scout but I'd rather not send them in bulk to Elastic.

**Comment by babenkoivan** [comment]
Hi @dannydinges, I think this option was redundant. Even it's always a bulk request, you can send either one document or a bunch of documents to Elastic:

```php
$model->searchable();   // one document is sent via bulk request
$models->searchable(); // a collection of documents is sent via bulk request
```

**Comment by dannydinges** [comment]
Fair enough that makes sense. I can make a copy of Scout's import command to make this work as you suggested. Thanks!
