### ISSUE TITLE
Automatic index creation option

### ISSUE THREAD

**Issue by GijsGoudzwaard** [babenkoivan/elastic-scout-driver#38]
## Description

Currently this scout driver throws an error when adding documents to an index that doesn't exist. By implementing this feature this elastic driver would create an empty index (without custom configuration) before populating it instead of throwing the error that the index doesn't exist. It would be fine to add a configuration option in the `config/elastic.client.php` that allows this.

This comment https://github.com/babenkoivan/elastic-scout-driver/issues/5 suggests to use elastic migrations. But an automatic solution would - in my use case - be better. It would only need to create an empty index before populating it. I don't need any custom configuration for my indices. Adding an extra package isn't needed for me since that package is better suited for projects that need custom index configurations. 

## Why

In our use case we have multiple projects (with multiple environments per project) creating indices on the fly. On average we have 5 indices per project per environment (we have 3 environments per project, so 15 indices per project on average). Currently we need to manually setup each index before we can use it. It would be a lot simpler if this package would create them on the fly, since we do not need a custom configuration, instead of throwing an error if it doesn't exist.

Also since other Laravel scout packages automatically create indices on the fly, it would therefore be logical that this package also does that since developers have a certain expectation of scout drivers.

**Comment by babenkoivan** [comment]
Hey @GijsGoudzwaard,

I think that indices are created on the fly by default, but this is controlled by Elasticsearch itself and not the client. Please, refer to [this documentation](https://www.elastic.co/guide/en/elasticsearch/reference/current/docs-index_.html#index-creation) for more details.

**Comment by GijsGoudzwaard** [comment]
I wasn't aware of that API. Though indices are only automatically created if they have a corresponding data stream configured. And according to the [documentation of elastic](https://www.elastic.co/guide/en/fleet/7.16/data-streams.html), data streams are only supposed to be used for logs, metrics or traces. Such isn't the case in my example. Thus I think it'd be best to support automatic index creation in this package. It would save me a lot of time and errors.

**Comment by babenkoivan** [comment]
@GijsGoudzwaard I could verify that indices are created by default. This simple test runs successfully without any migrations or manual work:

```php
factory(Book::class, rand(2, 10))->state('belongs_to_author')->create();

$target = factory(Book::class)->state('belongs_to_author')->create(['title' => uniqid('test')]);
$found = Book::search($target->title)->orderBy('id')->get();

$this->assertCount(1, $found);
$this->assertEquals($target->toArray(), $found->first()->toArray());
```

The only downside is that indices are created with auto-mapping, which might be not ideal.
