### ISSUE TITLE
Support for Lumen framework

### ISSUE THREAD

**Issue by AIV-T-Shark** [babenkoivan/elastic-scout-driver#4]
Is there any way to use the package with lumen framework?

**Comment by babenkoivan** [comment]
Hi @AIV-T-Shark, Lumen wasn't a primary goal, but I believe it can be done.

It will require some manual configuration steps, that's for sure. I'll test it and then prepare a wiki `how to` page with the guidelines. This feature is low priority though, so do not expect it to be done quickly.

**Comment by babenkoivan** [comment]
Hi there! 

I've just created a [wiki page with Lumen installation instructions](https://github.com/babenkoivan/elastic-scout-driver/wiki/Lumen-Installation). I tried it with the latest Lumen version and it worked.
