### ISSUE TITLE
unit testing

### ISSUE THREAD

**Issue by vortechron** [babenkoivan/elastic-scout-driver#41]
hi, I have no idea how to do unit testing for API that uses your package inside the controller. how to do test exactly with elasticsearch?

currently I just check if (!app()->environment() == 'testing'), skip the elasticsearch part. which is not a best solution.

**Comment by babenkoivan** [comment]
Hi @vortechron, 

I can only give you a direction. You can mock `ElasticScoutDriver\Engine` or `ElasticAdapter\Documents\DocumentManager` and then replace the binding in the service container before hitting the endpoint, e.g. `app()->instance(ElasticScoutDriver\Engine::class, $myEngineMock)`. `$myEngineMock` should have expectations for methods you use, i.e. `search` or `paginate`.

I hope this helps 🙂
