### ISSUE TITLE
Any plans on upgrading to ES8?

### ISSUE THREAD

**Issue by leeovery** [babenkoivan/elastic-scout-driver#42]
Hey!

Thanks for writing some really great software here.

Just wondering if there are plans to upgrade to ES8? Will help me figure out if I need to write my own adapters or not as we are planning on upgrading.

I havent tested with ES8 yet. Its quite possible that things still work. But thought Id reach out as a first step to get your thoughts.

Cheers
Lee

**Comment by babenkoivan** [comment]
Hey @leeovery, ES8 is on my roadmap.

I haven't tested with ES8 myself, but as you've said, it most likely works out of the box.

**Comment by leeovery** [comment]
Great. Thanks for the reply!

I haven't tested it myself yet. Few other things to do then I'll give it a whirl. 

Happy to do some PRs if I come across any issues. 

Thanks again.

**Comment by babenkoivan** [comment]
ES8 is supported since [v3.0.0](https://github.com/babenkoivan/elastic-scout-driver/releases/tag/v3.0.0) 🙂
