### ISSUE TITLE
how to create index with analyzer

### ISSUE THREAD

**Issue by shinnlu** [babenkoivan/elastic-scout-driver#43]
Hi,
in the previous package, i can [create index configurator](https://github.com/babenkoivan/scout-elasticsearch-driver#index-configurator):
`php artisan make:index-configurator MyIndexConfigurator`
then upload the index to elasticsearch:
`php artisan elastic:create-index "App\MyIndexConfigurator"`
how can i do this now?

the command `php artisan scout:index xxxxx` don't accept "Index Configurator file" from old package.
![image](https://user-images.githubusercontent.com/570246/164588433-9370547a-abe5-4564-b34d-b0418dac4fea.png)

**Comment by babenkoivan** [comment]
Hi @shinnlu, it is done differently now. You can use the [elastic-migrations](https://github.com/babenkoivan/elastic-migrations) package to create an index.

**Comment by shinnlu** [comment]
thank you for response, i will try it later.
