### ISSUE TITLE
how to enable SSL cert in configs ?

### ISSUE THREAD

**Issue by fadakar** [babenkoivan/elastic-scout-driver#47]
I have an error when trying to connect elastic 8.4 with elastic-scout-driver

 cURL error 60: SSL certificate problem: self signed certificate in certificate chain (see https://curl.haxx.se/libcurl/c/libcurl-errors.html) for https://localhost:9200/product_product_idx

how can I set SSL cert? please help me, thanks

**Comment by babenkoivan** [comment]
Hi @fadakar, 

if you need to connect to elasticsearch installed locally, you can use HTTP or disable SSL verification by adjusting the `elastic.client.php` config as follows:

```php
return [
    'default' => env('ELASTIC_CONNECTION', 'default'),
    'connections' => [
        'default' => [
            'hosts' => [
                env('ELASTIC_HOST', 'localhost:9200'),
            ],
            'options' => [
                'ssl_verify' => false,
            ],
        ],
    ],
];
```

I'm closing it as there is no feature needed.

**Comment by ak868308** [comment]
Where I can see all the options (keys) for elastic.client.php I am facing issue with handshake while I am providing .crt CABudnle also still dont know how to debug why I am getting 403

**Comment by babenkoivan** [comment]
Hi @ak868308, 

[elastic-client](https://github.com/babenkoivan/elastic-client) uses [the official php client](https://github.com/elastic/elasticsearch-php) under the hood. Each connection is built using the hash based configuration as described [here](https://www.elastic.co/docs/reference/elasticsearch/clients/php/node_pool#config-hash).

The available options are defined in [the client builder](https://github.com/elastic/elasticsearch-php/blob/main/src/ClientBuilder.php). According to [this method](https://github.com/elastic/elasticsearch-php/blob/main/src/ClientBuilder.php#L158), `setXxx($y)` is translated to `"xxx" => $y` in the configuration hash.

I hope this helps!
