### ISSUE TITLE
How to set basic authentication?

### ISSUE THREAD

**Issue by anjaszip** [babenkoivan/elastic-scout-driver#48]

**Comment by mofolo** [comment]
You can customise the Elastic Client to do this, the same if you're using the Elastic Cloud versions.

The Driver Repo uses the following client:
https://github.com/babenkoivan/elastic-client

Note in the Readme that you can register your own service provider to intercept the client - this is where you can set Basic Authentication

I also had to require `php-http/guzzle7-adapter` in order for the Async Client to work.

**Comment by babenkoivan** [comment]
It should be possible to provide credentials in the `elastic.client.php` file as follows:

```php
return [
    'default' => env('ELASTIC_CONNECTION', 'default'),
    'connections' => [
        'default' => [
            'hosts' => [
                env('ELASTIC_HOST', 'localhost:9200'),
            ],
            'basicAuthentication' => [
                'my_name',
                'my_password',
            ],
        ],
    ],
];
```

Closing this as no feature is needed.
