### ISSUE TITLE
406 Not Acceptable application/vnd.elasticsearch+json

### ISSUE THREAD

**Issue by AhmadMahdi963** [babenkoivan/elastic-scout-driver#50]
Hi

| Software         | Version
| --------------| ---------------
| PHP                 | 8.1
| Elasticsearch  | 7.10.2
| Laravel            | 9.26.1
| Laravel Scout | 9.4

After setup this package and the **elastic-migrations** the **_php artisan elastic:migrate_** command  gave this error

```

Migrating: 2022_09_25_163212_create_event_index

Elastic\Elasticsearch\Exception\ClientResponseException 

406 Not Acceptable: {"error":"Content-Type header [application/vnd.elasticsearch+json; compatible-with=8] is not supported","status":406}


```

My elasticsearch is 7.10.2 because I use the AWS OpenSearch

thanks.

**Comment by mohammadrasoulasghari** [comment]
I have the same problem
