### ISSUE TITLE
Support for laravel 10

### ISSUE THREAD

**Issue by NielsSmits1** [babenkoivan/elastic-scout-driver#51]
I would like to upgrade my existing projects to laravel 10 in the coming weeks, but I already noticed that this package does not support laravel 10 yet.

Would it be possible to add support for laravel 10?

**Comment by babenkoivan** [comment]
Hey @NielsSmits1, I've just tested all packages with Laravel 10 and it seems that all existing functionality works as expected. Feel free to upgrade your projects to Laravel 10, just make sure you use the latest package version 🙂
