### ISSUE TITLE
How do you use terminate_after with boolSearch

### ISSUE THREAD

**Issue by r-nicol** [babenkoivan/elastic-scout-driver#52]
I have searched the code and the documentation, but can not see anyway to add terminate_after to the request. Is this missing from the code or is there a way to do it? I am attempt to do a query like:
{
  "terminate_after": 60,
  "size": 20, 
  "query": {
    "bool": {
      "must": [
        {
          "nested": {
            "path": "search_filters",
            "query": {
              "bool": {
                "must": [
                  {
                    "match": {
                      "search_filters.key": "test"
                    }
                  },
                  {
                    "match": {
                      "search_filters.value": "option1"
                    }
                  }
                ]
              }
            }
          }
        },
        {
          "terms": {
            "listing_type_id": [
              "1",
              "2",
              "3"
            ]
          }
        }
      ]
    }
  },
  "aggs": {
    "sample": {
      "sampler": {
        "shard_size": 60
      },
      "aggs": {
        "filters": {
          "nested": {
            "path": "search_filters"
          },
          "aggs": {
            "search_keys": {
              "terms": {
                "field": "search_filters.key"
              },
              "aggs": {
                "search_values": {
                  "terms": {
                    "field": "search_filters.value"
                  }
                }
              }
            }
          }
        }
      }
    }
  },
  "sort": {
    "_geo_distance": {
      "coordinates": {
        "lat": "53.2",
        "lon": "-2.2"
      },
      "order": "asc",
      "unit": "km",
      "mode": "min"
    }
  }
}

**Comment by babenkoivan** [comment]
Her @r-nicol, there was no possibility to set `terminate_after` before, but I've just released [v4.4.0](https://github.com/babenkoivan/elastic-scout-driver-plus/releases/tag/v4.4.0) that supports this feature 🙂

**Please note** that you need to use [elastic-scout-driver-plus](https://github.com/babenkoivan/elastic-scout-driver-plus) package in addition to `elastic-scout-driver` to be able to set this parameter.

**Comment by r-nicol** [comment]
Excellent thanks for the update.
