### ISSUE TITLE
Cant install in laravel9

### ISSUE THREAD

**Issue by hanita0o0** [babenkoivan/elastic-scout-driver#54]
when i install this package see this error:
 Problem 1
    - elasticsearch/elasticsearch[v8.0.0, ..., v8.7.1] require psr/http-message ^1.0 -> found psr/http-message[1.0, 1.0.1, 1.1] but the package is fixed to
 2.0 (lock file version) by a partial update and that version does not match. Make sure you list it as an argument for the update command.
    - babenkoivan/elastic-adapter[v3.2.0, ..., v3.5.0] require babenkoivan/elastic-client ^2.1 -> satisfiable by babenkoivan/elastic-client[v2.1.0].       
    - babenkoivan/elastic-scout-driver-plus v4.5.0 requires babenkoivan/elastic-adapter ^3.4 -> satisfiable by babenkoivan/elastic-adapter[v3.4.0, v3.5.0].
    - babenkoivan/elastic-client v2.1.0 requires elasticsearch/elasticsearch ^8.0 -> satisfiable by elasticsearch/elasticsearch[v8.0.0, ..., v8.7.1].      
    - Root composer.json requires babenkoivan/elastic-scout-driver-plus ^4.5 -> satisfiable by babenkoivan/elastic-scout-driver-plus[v4.5.0].
please help me

**Comment by Saquib90** [comment]
try to delete the composer.lock file then try to install....

**Comment by babenkoivan** [comment]
Hi @hanita0o0, thank you for reporting the issue! This package uses [elasticsearch-php](https://github.com/elastic/elasticsearch-php) as a dependency, it requires `psr/http-message: ^1.0`, but it conflicts with what Laravel is currently using. I've created an issue [here](https://github.com/elastic/elasticsearch-php/issues/1316), please upvote it to get it resolved faster. 

Meanwhile, you can downgrade `psr/http-message` to version 1 by using `-W` parameter when installing the package:

```bash
composer require -W babenkoivan/elastic-scout-driver
```

**Comment by hanita0o0** [comment]
hi thanks for replying. i use composer require
elasticsearch/elasticsearch:v8.7.1 but yet need  psr/http-message ^1.0.
----- now i  forced  downgrade psr/http-message to version 1 .

**Comment by babenkoivan** [comment]
This issue should be resolved now https://github.com/elastic/elasticsearch-php/issues/1316.
