### ISSUE TITLE
Can't migrate properly

### ISSUE THREAD

**Issue by Saquib90** [babenkoivan/elastic-scout-driver#55]
i was using rennokki/elasticscout for laravel 8 ,   then i am migrating to laravel 10 in my project.

in laravel 8 project rennokki/elasticscout but it not maintained anymore so i try to install babankoivan/elastic-scout-driver.

it is installed but not proper know how to migrate my codebase to babankoivan/elastic-scout-driver and what are the changes i required to work properly with the babankoivan driver .

need help

**Comment by babenkoivan** [comment]
Hi @Saquib90, `rennokki/elasticscout` and `elastic-scout-driver` are two separate projects. I can only share with you some documentation links that might give you an idea of what needs to be changed:

* [Laravel Scout documentation](https://laravel.com/docs/master/scout)
* [Elastic Driver](https://github.com/babenkoivan/elastic-scout-driver)
* [Extended Elastic Driver](https://github.com/babenkoivan/elastic-scout-driver-plus)
* [Elastic Migrations](https://github.com/babenkoivan/elastic-migrations)
