### ISSUE TITLE
error when installing with laravel 10.x

### ISSUE THREAD

**Issue by metif12** [babenkoivan/elastic-scout-driver#56]
when installing with composer:

 Problem 1
    - elasticsearch/elasticsearch[v8.0.0, ..., v8.7.1] require psr/http-message ^1.0 -> found psr/http-message[1.0, 1.0.1, 1.1] but the package is fixed to 2.0 (lock file version) by a partial update and that ve
rsion does not match. Make sure you list it as an argument for the update command.
    - babenkoivan/elastic-adapter[v3.2.0, ..., v3.5.0] require babenkoivan/elastic-client ^2.1 -> satisfiable by babenkoivan/elastic-client[v2.1.0].
    - babenkoivan/elastic-scout-driver v3.1.0 requires babenkoivan/elastic-adapter ^3.2 -> satisfiable by babenkoivan/elastic-adapter[v3.2.0, v3.3.0, v3.4.0, v3.5.0].
    - babenkoivan/elastic-client v2.1.0 requires elasticsearch/elasticsearch ^8.0 -> satisfiable by elasticsearch/elasticsearch[v8.0.0, ..., v8.7.1].
    - Root composer.json requires babenkoivan/elastic-scout-driver ^3.1 -> satisfiable by babenkoivan/elastic-scout-driver[v3.1.0].

Use the option --with-all-dependencies (-W) to allow upgrades, downgrades and removals for packages currently locked to specific versions.
You can also try re-running composer require with an explicit version constraint, e.g. "composer require babenkoivan/elastic-scout-driver:*" to figure out if any version is installable, or "composer require babe
nkoivan/elastic-scout-driver:^2.1" if you know which you need.

**Comment by babenkoivan** [comment]
Hey @metif12, this has been already reported [here](https://github.com/babenkoivan/elastic-scout-driver/issues/54). Closing as a duplicate.
