### ISSUE TITLE
Up-gradation from babenkoivan/scout-elasticsearch-driver to this pacakge 

### ISSUE THREAD

**Issue by abdullah99R** [babenkoivan/elastic-scout-driver#57]
Hey I got a old laravel application that is using babenkoivan/scout-elasticsearch-driver. I was updating the laravel version from 5.x to 8.x and found that the package no longer maintained and author suggesting to use this one instead. Is there any up-gradation  guide that I need to follow

**Comment by babenkoivan** [comment]
Hi @abdullah99R, unfortunately, there is no step-by-step guide that you could follow, but I can recommend you to read [this article](https://medium.com/itnext/the-ultimate-guide-to-elasticsearch-in-laravel-application-ee636b79419c) to get familiar with the new approach. It is a bit outdated, but I think you can get the main idea of how things work now.
