### ISSUE TITLE
Please provide proper documentation for initial setup.

### ISSUE THREAD

**Issue by YogeshwarHz** [babenkoivan/elastic-scout-driver#58]
Need proper documentation on how to use this package other related package to fully utilize its features via laravel scout 
for laravel 8 , 9 and 10.It is quite confusing since it  while setting up for beginners.
Facing this even after properly following the documentation

@babenkoivan

**Comment by babenkoivan** [comment]
Hey @YogeshwarHz, I can recommend you to read the [official Laravel Scout documentation](https://laravel.com/docs/master/scout) and [this article](https://itnext.io/the-ultimate-guide-to-elasticsearch-in-laravel-application-ee636b79419c). Unfortunately, the article is a little bit outdated (some things are done differently now), but you can get a basic idea how packages work together.
