### ISSUE TITLE
How to Configuring Mappings

### ISSUE THREAD

**Issue by Aniket-IN** [babenkoivan/elastic-scout-driver#59]
Hi 👋, 

First of all thank for this amazing pacakge. 
I just started learning Elastic Search and found out your package which makes it's very easy to integrate Elastic Search in Laravel. 

I just need a bit help 🙂,
I'm a bit confused, how/where do I configure the index mappings?

Thanks again 😊

**Comment by babenkoivan** [comment]
Hi @Aniket-IN 👋🏻

I recommend you get familiar with this package https://github.com/babenkoivan/elastic-migrations. It allows you to write migrations for your indexes including mapping and settings.
