### ISSUE TITLE
Overwriting `makeQuery` method to use different query type

### ISSUE THREAD

**Issue by Aniket-IN** [babenkoivan/elastic-scout-driver#60]
Hi 👋, 

Thank you so much for the amazing ecosystem of Elasticsearch packages 🤗.

I see by default the `search` method is using query type `query_string`,

I think this [`makeQuery`](https://github.com/babenkoivan/elastic-scout-driver/blob/485eb1fa671e9b907bcad78a4afba1ed481f47fb/src/Factories/SearchParametersFactory.php#L41-L64) method is responsible for that, 
https://github.com/babenkoivan/elastic-scout-driver/blob/485eb1fa671e9b907bcad78a4afba1ed481f47fb/src/Factories/SearchParametersFactory.php#L41-L64

So, is there any way, we can overwrite that method? 🤔

I checked the `elastic-scout-driver-plus` package , that allows us to write custom queries, 
But, that doesnt allow us to use the scout methods e.g `where`, `whereIn` etc..

That package is very useful in writing complex queries, 
However sometimes just to write basic query with the `search` method and to be able to override some stuff will be really helpful. 😊

Thanks again 🙏

**Comment by babenkoivan** [comment]
Hi @Aniket-IN,

you can define your own `SearchParametersFactory` with a custom implementation of `makeQuery` and register it in the service provider.

I hope this helps 🙂
