### ISSUE TITLE
Laravel 11 support

### ISSUE THREAD

**Issue by leitommi** [babenkoivan/elastic-scout-driver#62]
Laravel 11 is out since March 12 2024
Is there a plan or timeline to support Laravel 11?

**Comment by babenkoivan** [comment]
Hey @leitommi, it's in progress 🙂

**Comment by babenkoivan** [comment]
Hi there 👋🏻 I've just released new major versions for all packages with Laravel 11 support, please check it out and let me know if you have any troubles 🙂
