### ISSUE TITLE
Support for OpenSearch (AWS)

### ISSUE THREAD

**Issue by kovinet** [babenkoivan/elastic-scout-driver#63]
I have been using older version of this package with ElasticSearch on AWS and it worked great. But now AWS rebranded this service to OpenSearch which is not anymore compatible with ES 8, as you can currently only upgrade from ES7 to OpenSearch 1.3.  

Are there any plans to also support OpenSearch or does this driver also work with OpenSearch on AWS or not?

**Comment by babenkoivan** [comment]
Hey @kovinet, this has been raised before. Unfortunately, OpenSearch support requires a lot of effort and time, which I currently don't have. Please, take a look at the comment [here](https://github.com/babenkoivan/elastic-scout-driver-plus/issues/139#issuecomment-1522951888).
