### ISSUE TITLE
 Support for unsigned_long Type in Elasticsearch Mapping

### ISSUE THREAD

**Issue by brfuat9** [babenkoivan/elastic-scout-driver#69]
While creating migrations, we often utilize the long type for numeric fields. However, it seems there is no unsigned_long type option available in the mapping configurations. This feature would be highly beneficial, especially for cases where we only deal with positive numeric values and need to maximize the range of values stored. Thanks.

https://www.elastic.co/guide/en/elasticsearch/reference/current/number.html

Sorry, I wrote this in the wrong place. I actually meant to post it here: https://github.com/babenkoivan/elastic-migrations/issues/58

**Comment by babenkoivan** [comment]
closing as a duplicate https://github.com/babenkoivan/elastic-migrations/issues/58
