### ISSUE TITLE
Remove elasticsearch/elasticsearch as a required package

### ISSUE THREAD

**Issue by GarethSomers** [babenkoivan/elastic-scout-driver#7]
I'm an amatuer at anything Elastic Search but as I understand the package `elasticsearch/elasticsearch` contains Elastic Search itself and not a supporting / complimenting library (but correct me if I'm wrong). In some cases I would not need Elastic Search installed (via composer) as I may have manually installed it or it's installed / provided as apart of the server provisioning. 

To provide developer's the maximum choice can we remove `elasticsearch/elasticsearch` from the required packages. It could instead be a suggested package?

I haven't throughly checked your other packages which related to Elastic Search. But this suggestion is accepted it should be extended to those other packages (e.g. https://github.com/babenkoivan/elastic-adapter).

**Comment by babenkoivan** [comment]
Hey @GarethSomers!

`elasticsearch/elasticsearch` is not more than a client for Elasticsearch REST API. It's not Elasticsearch software itself, so you are free to install it by yourself or use the provided one.

This driver and Elastic Adapter heavily rely on `elasticsearch/elasticsearch` and it's not possible to remove this dependency.

**Comment by GarethSomers** [comment]
Okay no worries thanks for the clarification
