### ISSUE TITLE
orderBy doesn't work

### ISSUE THREAD

**Issue by Juanperezc** [babenkoivan/elastic-scout-driver#9]
Hi, I'm trying to use the orderBy method by date and it doesn't work for me, I don't know if it's a bug or a requirement

**Comment by babenkoivan** [comment]
Hi @Juanperezc, I've just checked and it works for me. Please ensure, that you have a [valid mapping for your date fields](https://www.elastic.co/guide/en/elasticsearch/reference/current/date.html).

**Comment by mauriciovillam** [comment]
Hello @babenkoivan , thank you for this great work. I'm trying to `orderBy('id', 'desc')` and I have this line in my index migration: `$mapping->integer('id')`. Do I need to do anything else in order to get the orderBy working? Because it currently isn't having any effect in my case.

**Comment by babenkoivan** [comment]
@mauriciovillam `id` should be included in the indexed array by default, of course if it's not excluded via `hidden` property or explicitly in `toSearchableArray` or `toArray`.

**Comment by FrittenKeeZ** [comment]
@babenkoivan I'm getting this error when trying to use `orderBy`:
```
No mapping found for [order] in order to sort on
```
I haven't setup any custom mapping, only using this package, and all the fields are exposed in `toSearchableArray`.
Any ideas what's going wrong?

**Comment by babenkoivan** [comment]
@FrittenKeeZ Elasticsearch doesn't like sorting on unmapped fields. You can either define a mapping (see [migrations package](https://github.com/babenkoivan/elastic-migrations)) or ignore the mapping in the `sortRaw` method:

```php
$searchResult = Book::rawSearch()
    ->query(['match_all' => new \stdClass()])
    ->sortRaw([['price' => ['order' => 'asc', 'unmapped_type' => true]]])
    ->execute();
```

**Comment by FrittenKeeZ** [comment]
@babenkoivan for now we've dropped manual ordering, as Elasticsearch seems to be rather good at ordering by best match, but later I might look at boosting certain fields.
